/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface MerkleTreeInterface extends utils.Interface {
  functions: {
    "isAllowed(bytes32[],address)": FunctionFragment;
    "merkleRoot()": FunctionFragment;
    "requireAllowlist()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "isAllowed" | "merkleRoot" | "requireAllowlist"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isAllowed",
    values: [PromiseOrValue<BytesLike>[], PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "merkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requireAllowlist",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "isAllowed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "merkleRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requireAllowlist",
    data: BytesLike
  ): Result;

  events: {};
}

export interface MerkleTree extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MerkleTreeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isAllowed(
      _proof: PromiseOrValue<BytesLike>[],
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    merkleRoot(overrides?: CallOverrides): Promise<[string]>;

    requireAllowlist(overrides?: CallOverrides): Promise<[boolean]>;
  };

  isAllowed(
    _proof: PromiseOrValue<BytesLike>[],
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  merkleRoot(overrides?: CallOverrides): Promise<string>;

  requireAllowlist(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    isAllowed(
      _proof: PromiseOrValue<BytesLike>[],
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    merkleRoot(overrides?: CallOverrides): Promise<string>;

    requireAllowlist(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    isAllowed(
      _proof: PromiseOrValue<BytesLike>[],
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    merkleRoot(overrides?: CallOverrides): Promise<BigNumber>;

    requireAllowlist(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    isAllowed(
      _proof: PromiseOrValue<BytesLike>[],
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    merkleRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    requireAllowlist(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
