/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockPoolsSol from "./MockPools.sol";
export type { mockPoolsSol };
export type { MockERC20 } from "./MockERC20";
export type { MockRouter } from "./MockRouter";
