/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  MerkleTree,
  MerkleTreeInterface,
} from "../../../contracts/lib/MerkleTree";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes32[]",
        name: "_proof",
        type: "bytes32[]",
      },
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "isAllowed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "merkleRoot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "requireAllowlist",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561000f575f80fd5b506001805460ff191681179055610307806100295f395ff3fe608060405234801561000f575f80fd5b506004361061003f575f3560e01c80630c9a94d2146100435780632eb4a7ab146100655780637fac20941461007c575b5f80fd5b6001546100509060ff1681565b60405190151581526020015b60405180910390f35b61006e60025481565b60405190815260200161005c565b61005061008a3660046101b1565b6040517fffffffffffffffffffffffffffffffffffffffff000000000000000000000000606083901b1660208201525f9081906034016040516020818303038152906040528051906020012090506101188585808060200260200160405190810160405280939291908181526020018383602002808284375f92019190915250506002549150849050610121565b95945050505050565b5f8261012d8584610136565b14949350505050565b5f81815b845181101561017a576101668286838151811061015957610159610248565b6020026020010151610182565b91508061017281610275565b91505061013a565b509392505050565b5f81831061019c575f8281526020849052604090206101aa565b5f8381526020839052604090205b9392505050565b5f805f604084860312156101c3575f80fd5b833567ffffffffffffffff808211156101da575f80fd5b818601915086601f8301126101ed575f80fd5b8135818111156101fb575f80fd5b8760208260051b850101111561020f575f80fd5b6020928301955093505084013573ffffffffffffffffffffffffffffffffffffffff8116811461023d575f80fd5b809150509250925092565b7f4e487b71000000000000000000000000000000000000000000000000000000005f52603260045260245ffd5b5f7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff82036102ca577f4e487b71000000000000000000000000000000000000000000000000000000005f52601160045260245ffd5b506001019056fea2646970667358221220bf45fcba60066e04022ff0cd0186f592ed37a3f3ad59a72eafb02f7b28d3a8ab64736f6c63430008140033";

type MerkleTreeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MerkleTreeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MerkleTree__factory extends ContractFactory {
  constructor(...args: MerkleTreeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<MerkleTree> {
    return super.deploy(overrides || {}) as Promise<MerkleTree>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MerkleTree {
    return super.attach(address) as MerkleTree;
  }
  override connect(signer: Signer): MerkleTree__factory {
    return super.connect(signer) as MerkleTree__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MerkleTreeInterface {
    return new utils.Interface(_abi) as MerkleTreeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MerkleTree {
    return new Contract(address, _abi, signerOrProvider) as MerkleTree;
  }
}
