/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace AequiLens {
  export type TokenMetadataStruct = {
    token: PromiseOrValue<string>;
    decimals: PromiseOrValue<BigNumberish>;
    symbol: PromiseOrValue<string>;
    name: PromiseOrValue<string>;
    exists: PromiseOrValue<boolean>;
  };

  export type TokenMetadataStructOutput = [
    string,
    number,
    string,
    string,
    boolean
  ] & {
    token: string;
    decimals: number;
    symbol: string;
    name: string;
    exists: boolean;
  };

  export type V2PoolDataStruct = {
    pool: PromiseOrValue<string>;
    reserve0: PromiseOrValue<BigNumberish>;
    reserve1: PromiseOrValue<BigNumberish>;
    token0: PromiseOrValue<string>;
    token1: PromiseOrValue<string>;
    exists: PromiseOrValue<boolean>;
  };

  export type V2PoolDataStructOutput = [
    string,
    BigNumber,
    BigNumber,
    string,
    string,
    boolean
  ] & {
    pool: string;
    reserve0: BigNumber;
    reserve1: BigNumber;
    token0: string;
    token1: string;
    exists: boolean;
  };

  export type V3PoolDataStruct = {
    pool: PromiseOrValue<string>;
    sqrtPriceX96: PromiseOrValue<BigNumberish>;
    tick: PromiseOrValue<BigNumberish>;
    liquidity: PromiseOrValue<BigNumberish>;
    token0: PromiseOrValue<string>;
    token1: PromiseOrValue<string>;
    fee: PromiseOrValue<BigNumberish>;
    exists: PromiseOrValue<boolean>;
  };

  export type V3PoolDataStructOutput = [
    string,
    BigNumber,
    number,
    BigNumber,
    string,
    string,
    number,
    boolean
  ] & {
    pool: string;
    sqrtPriceX96: BigNumber;
    tick: number;
    liquidity: BigNumber;
    token0: string;
    token1: string;
    fee: number;
    exists: boolean;
  };
}

export interface AequiLensInterface extends utils.Interface {
  functions: {
    "batchCheckAllowances(address[],address,address)": FunctionFragment;
    "batchCheckTokenBalances(address[],address)": FunctionFragment;
    "batchGetTokenMetadata(address[])": FunctionFragment;
    "batchGetV2PoolData(address[])": FunctionFragment;
    "batchGetV3PoolData(address[])": FunctionFragment;
    "getTokenMetadataSingle(address)": FunctionFragment;
    "getV2PoolDataSingle(address)": FunctionFragment;
    "getV3PoolDataSingle(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "batchCheckAllowances"
      | "batchCheckTokenBalances"
      | "batchGetTokenMetadata"
      | "batchGetV2PoolData"
      | "batchGetV3PoolData"
      | "getTokenMetadataSingle"
      | "getV2PoolDataSingle"
      | "getV3PoolDataSingle"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "batchCheckAllowances",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCheckTokenBalances",
    values: [PromiseOrValue<string>[], PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "batchGetTokenMetadata",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchGetV2PoolData",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchGetV3PoolData",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenMetadataSingle",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getV2PoolDataSingle",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getV3PoolDataSingle",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchCheckAllowances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCheckTokenBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchGetTokenMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchGetV2PoolData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchGetV3PoolData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenMetadataSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getV2PoolDataSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getV3PoolDataSingle",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AequiLens extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AequiLensInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    batchCheckAllowances(
      tokens: PromiseOrValue<string>[],
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    batchCheckTokenBalances(
      tokens: PromiseOrValue<string>[],
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    batchGetTokenMetadata(
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [AequiLens.TokenMetadataStructOutput[]] & {
        results: AequiLens.TokenMetadataStructOutput[];
      }
    >;

    batchGetV2PoolData(
      pools: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [AequiLens.V2PoolDataStructOutput[]] & {
        results: AequiLens.V2PoolDataStructOutput[];
      }
    >;

    batchGetV3PoolData(
      pools: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<
      [AequiLens.V3PoolDataStructOutput[]] & {
        results: AequiLens.V3PoolDataStructOutput[];
      }
    >;

    getTokenMetadataSingle(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [AequiLens.TokenMetadataStructOutput] & {
        data: AequiLens.TokenMetadataStructOutput;
      }
    >;

    getV2PoolDataSingle(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [AequiLens.V2PoolDataStructOutput] & {
        data: AequiLens.V2PoolDataStructOutput;
      }
    >;

    getV3PoolDataSingle(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [AequiLens.V3PoolDataStructOutput] & {
        data: AequiLens.V3PoolDataStructOutput;
      }
    >;
  };

  batchCheckAllowances(
    tokens: PromiseOrValue<string>[],
    owner: PromiseOrValue<string>,
    spender: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  batchCheckTokenBalances(
    tokens: PromiseOrValue<string>[],
    account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  batchGetTokenMetadata(
    tokens: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<AequiLens.TokenMetadataStructOutput[]>;

  batchGetV2PoolData(
    pools: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<AequiLens.V2PoolDataStructOutput[]>;

  batchGetV3PoolData(
    pools: PromiseOrValue<string>[],
    overrides?: CallOverrides
  ): Promise<AequiLens.V3PoolDataStructOutput[]>;

  getTokenMetadataSingle(
    token: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<AequiLens.TokenMetadataStructOutput>;

  getV2PoolDataSingle(
    pool: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<AequiLens.V2PoolDataStructOutput>;

  getV3PoolDataSingle(
    pool: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<AequiLens.V3PoolDataStructOutput>;

  callStatic: {
    batchCheckAllowances(
      tokens: PromiseOrValue<string>[],
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    batchCheckTokenBalances(
      tokens: PromiseOrValue<string>[],
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    batchGetTokenMetadata(
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<AequiLens.TokenMetadataStructOutput[]>;

    batchGetV2PoolData(
      pools: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<AequiLens.V2PoolDataStructOutput[]>;

    batchGetV3PoolData(
      pools: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<AequiLens.V3PoolDataStructOutput[]>;

    getTokenMetadataSingle(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<AequiLens.TokenMetadataStructOutput>;

    getV2PoolDataSingle(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<AequiLens.V2PoolDataStructOutput>;

    getV3PoolDataSingle(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<AequiLens.V3PoolDataStructOutput>;
  };

  filters: {};

  estimateGas: {
    batchCheckAllowances(
      tokens: PromiseOrValue<string>[],
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchCheckTokenBalances(
      tokens: PromiseOrValue<string>[],
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchGetTokenMetadata(
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchGetV2PoolData(
      pools: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchGetV3PoolData(
      pools: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenMetadataSingle(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getV2PoolDataSingle(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getV3PoolDataSingle(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    batchCheckAllowances(
      tokens: PromiseOrValue<string>[],
      owner: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchCheckTokenBalances(
      tokens: PromiseOrValue<string>[],
      account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchGetTokenMetadata(
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchGetV2PoolData(
      pools: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchGetV3PoolData(
      pools: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenMetadataSingle(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getV2PoolDataSingle(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getV3PoolDataSingle(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
